### ISSUE TITLE
About PDB data

### ISSUE THREAD

**Issue by terry-r123** [BioinfoMachineLearning/DIPS-Plus#14]
Hi @amorehead , I want to know why there are multiple pdb files for the same protein, for example 5zz9.pdb1,5zz9.pdb2,5zz9.pdb3, what is the difference between them?

**Comment by amorehead** [comment]
@terry-r123,

The reason for this is that we can derive multiple pairs of protein chains from a single large complex. For example, from a complex containing 3 chains, we can potentially extract three separate PDB files for training describing the three possible combinations of interacting protein chains.

**Comment by terry-r123** [comment]
@amorehead  Thanks!
